#!/usr/bin/env bash
# Regenerates task-tracking/registry.md from per-task status files.
# Called by Claude Code hooks whenever a status file is written or update_task is called.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TRACKING_DIR="$PROJECT_ROOT/task-tracking"
REGISTRY="$TRACKING_DIR/registry.md"

[[ -d "$TRACKING_DIR" ]] || exit 0

python3 - "$TRACKING_DIR" "$REGISTRY" <<'PYEOF'
import sys, os, re
from datetime import date

tracking_dir, registry_path = sys.argv[1], sys.argv[2]

VALID = {'CREATED','IN_PROGRESS','IMPLEMENTED','IN_REVIEW','FIXING','COMPLETE','FAILED','BLOCKED','CANCELLED'}
TODAY = date.today().isoformat()

# Parse existing registry for fallback data
reg = {}  # id -> {created, type, desc, model}
if os.path.exists(registry_path):
    for line in open(registry_path):
        m = re.match(r'^\|\s*(TASK_\d{4}_\d{3})\s*\|\s*(\S+)\s*\|\s*(\S+)\s*\|\s*(.+?)\s*\|\s*(\d{4}-\d{2}-\d{2})\s*\|\s*([^|]+?)\s*\|', line)
        if m:
            reg[m.group(1)] = {
                'status': m.group(2), 'type': m.group(3),
                'desc': m.group(4).strip(), 'created': m.group(5),
                'model': m.group(6).strip(),
            }

def parse_task_md(path):
    if not os.path.exists(path):
        return {}
    txt = open(path).read()
    result = {}
    m = re.search(r'^#\s+Task:\s+(.+)', txt, re.MULTILINE)
    if m: result['desc'] = m.group(1).strip()
    m = re.search(r'^\|\s*Type\s*\|\s*([^|]+?)\s*\|', txt, re.MULTILINE)
    if m: result['type'] = m.group(1).strip()
    m = re.search(r'^\|\s*Model\s*\|\s*([^|]+?)\s*\|', txt, re.MULTILINE)
    if m: result['model'] = m.group(1).strip()
    return result

tasks = sorted([d for d in os.listdir(tracking_dir) if re.match(r'^TASK_\d{4}_\d{3}$', d)])

lines = [
    '<!-- DO NOT EDIT — generated by nitro-fueled status -->',
    '# Task Registry',
    '',
    '| Task ID       | Status      | Type    | Description                        | Created    | Model |',
    '|---------------|-------------|---------|------------------------------------|------------|-------|',
]

for task_id in tasks:
    task_dir = os.path.join(tracking_dir, task_id)
    status_file = os.path.join(task_dir, 'status')
    status = 'CREATED'
    if os.path.exists(status_file):
        raw = open(status_file).read().strip()
        status = raw if raw in VALID else 'CREATED'
    elif task_id in reg:
        status = reg[task_id]['status'] if reg[task_id]['status'] in VALID else 'CREATED'

    meta = parse_task_md(os.path.join(task_dir, 'task.md'))
    fallback = reg.get(task_id, {})

    typ = meta.get('type') or fallback.get('type', '')
    desc = (meta.get('desc') or fallback.get('desc', '')).replace('|', '\\|')
    model = meta.get('model') or fallback.get('model', 'default')
    created = fallback.get('created', TODAY)

    lines.append(f'| {task_id} | {status:<11} | {typ:<7} | {desc} | {created} | {model} |')

lines.append('')

tmp = registry_path + '.tmp'
with open(tmp, 'w') as f:
    f.write('\n'.join(lines))
os.replace(tmp, registry_path)
print(f'[regen-registry] wrote {len(tasks)} tasks to registry.md', file=sys.stderr)
PYEOF
