import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { Flags } from '@oclif/core';
import { BaseCommand } from '../base-command.js';
import { logger } from '../utils/logger.js';

export default class Export extends BaseCommand {
  public static override description = 'Export DB state to markdown files for human review';

  public static override flags = {
    tasks: Flags.boolean({ description: 'Export task list to task-tracking/registry.md', default: false }),
    sessions: Flags.boolean({ description: 'Export session summaries', default: false }),
  };

  public static override usage = ['', '--tasks', '--sessions'];

  public static override examples = [
    { description: 'Export all (tasks + sessions)', command: '<%= config.bin %> <%= command.id %>' },
    { description: 'Export task list only', command: '<%= config.bin %> <%= command.id %> --tasks' },
  ];

  public async run(): Promise<void> {
    const { flags } = await this.parse(Export);
    const cwd = process.cwd();
    const dbPath = resolve(cwd, '.nitro', 'cortex.db');

    if (!existsSync(dbPath)) {
      logger.error('Error: cortex DB not found. Run `npx nitro-fueled init` first.');
      process.exitCode = 1;
      return;
    }

    let db: import('better-sqlite3').Database;
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const Database = require('better-sqlite3') as typeof import('better-sqlite3');
      db = new Database(dbPath, { readonly: true });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message.slice(0, 200) : String(err).slice(0, 200);
      logger.error(`Error: could not open cortex DB: ${msg}`);
      process.exitCode = 1;
      return;
    }

    const exportAll = !flags.tasks && !flags.sessions;
    const exportTasks = exportAll || flags.tasks;
    const exportSessions = exportAll || flags.sessions;

    try {
      if (exportTasks) {
        this.exportTaskRegistry(db, cwd);
      }
      if (exportSessions) {
        this.exportSessionSummary(db, cwd);
      }
    } finally {
      db.close();
    }
  }

  private exportTaskRegistry(db: import('better-sqlite3').Database, cwd: string): void {
    const rows = db.prepare('SELECT id, status, type, title, created_at FROM tasks ORDER BY id').all() as Array<{
      id: string; status: string; type: string; title: string; created_at: string;
    }>;

    const lines = rows.map((row) => {
      const created = row.created_at?.includes('T') ? row.created_at.split('T')[0] : (row.created_at ?? 'Unknown');
      const safeTitle = (row.title ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
      return `| ${row.id} | ${(row.status ?? 'CREATED').padEnd(11)} | ${(row.type ?? '').padEnd(7)} | ${safeTitle} | ${created} |`;
    });

    const output = [
      '<!-- DO NOT EDIT — generated by nitro-fueled export -->',
      '# Task Registry',
      '',
      '| Task ID       | Status      | Type    | Title                              | Created    |',
      '|---------------|-------------|---------|------------------------------------|---------  -|',
      ...lines,
      '',
    ].join('\n');

    const registryPath = resolve(cwd, 'task-tracking', 'registry.md');
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const { mkdirSync, writeFileSync } = require('node:fs') as typeof import('node:fs');
      mkdirSync(resolve(cwd, 'task-tracking'), { recursive: true });
      writeFileSync(registryPath, output, 'utf-8');
      logger.log(`Exported: ${rows.length} tasks → task-tracking/registry.md`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message.slice(0, 200) : String(err).slice(0, 200);
      logger.error(`Warning: could not write registry.md: ${msg}`);
    }
  }

  private exportSessionSummary(db: import('better-sqlite3').Database, cwd: string): void {
    const sessions = db.prepare(
      `SELECT id, source, started_at, ended_at, loop_status, tasks_terminal
       FROM sessions ORDER BY started_at DESC LIMIT 20`,
    ).all() as Array<{
      id: string; source: string; started_at: string; ended_at: string | null;
      loop_status: string; tasks_terminal: number;
    }>;

    if (sessions.length === 0) {
      logger.log('Sessions: none found');
      return;
    }

    const lines = sessions.map((s) => {
      const started = s.started_at?.includes('T') ? s.started_at.replace('T', ' ').slice(0, 19) : s.started_at;
      const ended = s.ended_at ? s.ended_at.replace('T', ' ').slice(0, 19) : 'running';
      return `| ${s.id} | ${(s.source ?? '').padEnd(10)} | ${s.loop_status.padEnd(8)} | ${s.tasks_terminal} | ${started} | ${ended} |`;
    });

    const output = [
      '<!-- DO NOT EDIT — generated by nitro-fueled export -->',
      '# Session Summary',
      '',
      '| Session ID | Source | Status | Tasks | Started | Ended |',
      '|------------|--------|--------|-------|---------|-------|',
      ...lines,
      '',
    ].join('\n');

    const summaryPath = resolve(cwd, 'task-tracking', 'sessions-summary.md');
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const { mkdirSync, writeFileSync } = require('node:fs') as typeof import('node:fs');
      mkdirSync(resolve(cwd, 'task-tracking'), { recursive: true });
      writeFileSync(summaryPath, output, 'utf-8');
      logger.log(`Exported: ${sessions.length} sessions → task-tracking/sessions-summary.md`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message.slice(0, 200) : String(err).slice(0, 200);
      logger.error(`Warning: could not write sessions-summary.md: ${msg}`);
    }
  }
}
