import {
  AgentAssignment,
  SubAgentAssignment,
  QuickPreset,
  ScopeTab,
  HierarchyLevel,
  ModelAssignmentsData,
} from '../models/model-assignment.model';

const CLAUDE_CLI_OPTGROUP = {
  groupLabel: 'Claude CLI',
  options: [
    { label: 'Claude CLI → Opus 4', value: 'cli-opus-4' },
    { label: 'Claude CLI → Sonnet 4', value: 'cli-sonnet-4' },
    { label: 'Claude CLI → Haiku 4', value: 'cli-haiku-4' },
  ],
} as const;

const API_ANTHROPIC_OPTGROUP = {
  groupLabel: 'API — Anthropic',
  options: [
    { label: 'API → Opus 4', value: 'api-opus-4' },
    { label: 'API → Sonnet 4', value: 'api-sonnet-4' },
    { label: 'API → Haiku 4', value: 'api-haiku-4' },
  ],
} as const;

const API_OPENAI_OPTGROUP = {
  groupLabel: 'API — OpenAI',
  options: [
    { label: 'API → GPT-4o', value: 'api-gpt4o' },
    { label: 'API → o3', value: 'api-o3' },
    { label: 'API → Codex Mini', value: 'api-codex-mini' },
  ],
} as const;

const OAUTH_COPILOT_OPTGROUP = {
  groupLabel: 'OAuth — GitHub Copilot',
  options: [
    { label: 'OAuth → Sonnet 4', value: 'oauth-sonnet-4' },
    { label: 'OAuth → GPT-4o', value: 'oauth-gpt4o' },
  ],
} as const;

const MOCK_SCOPE_TABS: readonly ScopeTab[] = [
  { label: 'Global Defaults', count: null, active: true },
  { label: 'Per-Role', count: 5, active: false },
  { label: 'Per-Team', count: 3, active: false },
  { label: 'Per-Project', count: 2, active: false },
  { label: 'Per-Task', count: 1, active: false },
];

const MOCK_HIERARCHY_LEVELS: readonly HierarchyLevel[] = [
  { label: 'Global', cssClass: 'l1' },
  { label: 'Per-Role', cssClass: 'l2' },
  { label: 'Per-Team', cssClass: 'l3' },
  { label: 'Per-Project', cssClass: 'l4' },
  { label: 'Per-Task', cssClass: 'l5' },
];

const MOCK_ASSIGNMENTS: readonly AgentAssignment[] = [
  {
    role: 'Orchestrator',
    category: 'Engine Core',
    icon: '⚡',
    iconClass: 'leadership',
    providerType: 'CLI',
    modelOptgroups: [CLAUDE_CLI_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'cli-opus-4',
    overrideLevel: 'GLOBAL DEFAULT',
    overrideNote: '',
    fallbackChain: ['GPT-4o', 'Sonnet 4'],
    costPerTask: 2.40,
    hasOverride: false,
  },
  {
    role: 'project-manager',
    category: 'Leadership',
    icon: '📋',
    iconClass: 'leadership',
    providerType: 'API',
    modelOptgroups: [API_ANTHROPIC_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'api-sonnet-4',
    overrideLevel: 'GLOBAL DEFAULT',
    overrideNote: '',
    fallbackChain: ['GPT-4o', 'Haiku 4'],
    costPerTask: 0.80,
    hasOverride: false,
  },
  {
    role: 'software-architect',
    category: 'Leadership',
    icon: '🏛️',
    iconClass: 'leadership',
    providerType: 'CLI',
    modelOptgroups: [CLAUDE_CLI_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'cli-opus-4',
    overrideLevel: 'ROLE OVERRIDE',
    overrideNote: 'best reasoning needed',
    fallbackChain: ['GPT-4o', 'Sonnet 4'],
    costPerTask: 3.10,
    hasOverride: true,
  },
  {
    role: 'team-leader',
    category: 'Leadership',
    icon: '👑',
    iconClass: 'leadership',
    providerType: 'CLI',
    modelOptgroups: [CLAUDE_CLI_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'cli-opus-4',
    overrideLevel: 'ROLE OVERRIDE',
    overrideNote: '',
    fallbackChain: ['o3', 'Sonnet 4'],
    costPerTask: 2.80,
    hasOverride: true,
  },
  {
    role: 'backend-developer',
    category: 'Development',
    icon: '⚙️',
    iconClass: 'development',
    providerType: 'API',
    modelOptgroups: [API_OPENAI_OPTGROUP, CLAUDE_CLI_OPTGROUP],
    selectedModel: 'api-codex-mini',
    overrideLevel: 'ROLE OVERRIDE',
    overrideNote: 'optimized for code gen',
    fallbackChain: ['Sonnet 4', 'GPT-4o'],
    costPerTask: 0.60,
    hasOverride: true,
  },
  {
    role: 'frontend-developer',
    category: 'Development',
    icon: '🎨',
    iconClass: 'development',
    providerType: 'CLI',
    modelOptgroups: [CLAUDE_CLI_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'cli-sonnet-4',
    overrideLevel: 'GLOBAL DEFAULT',
    overrideNote: '',
    fallbackChain: ['GPT-4o', 'Haiku 4'],
    costPerTask: 0.80,
    hasOverride: false,
  },
  {
    role: 'database-specialist',
    category: 'Development',
    icon: '🗄️',
    iconClass: 'development',
    providerType: 'API',
    modelOptgroups: [API_ANTHROPIC_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'api-sonnet-4',
    overrideLevel: 'GLOBAL DEFAULT',
    overrideNote: '',
    fallbackChain: ['GPT-4o', 'Haiku 4'],
    costPerTask: 0.80,
    hasOverride: false,
  },
  {
    role: 'code-style-reviewer',
    category: 'Quality',
    icon: '✅',
    iconClass: 'quality',
    providerType: 'API',
    modelOptgroups: [API_ANTHROPIC_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'api-haiku-4',
    overrideLevel: 'ROLE OVERRIDE',
    overrideNote: 'fast & cheap',
    fallbackChain: ['Sonnet 4'],
    costPerTask: 0.12,
    hasOverride: true,
  },
  {
    role: 'logic-reviewer',
    category: 'Quality',
    icon: '🔍',
    iconClass: 'quality',
    providerType: 'API',
    modelOptgroups: [API_ANTHROPIC_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'api-sonnet-4',
    overrideLevel: 'GLOBAL DEFAULT',
    overrideNote: '',
    fallbackChain: ['GPT-4o', 'Haiku 4'],
    costPerTask: 0.80,
    hasOverride: false,
  },
  {
    role: 'security-reviewer',
    category: 'Quality',
    icon: '🛡️',
    iconClass: 'quality',
    providerType: 'CLI',
    modelOptgroups: [CLAUDE_CLI_OPTGROUP, API_OPENAI_OPTGROUP],
    selectedModel: 'cli-opus-4',
    overrideLevel: 'ROLE OVERRIDE',
    overrideNote: 'security needs best reasoning',
    fallbackChain: ['GPT-4o', 'Sonnet 4'],
    costPerTask: 1.90,
    hasOverride: true,
  },
  {
    role: 'devops-engineer',
    category: 'DevOps',
    icon: '🚀',
    iconClass: 'devops',
    providerType: 'OAuth',
    modelOptgroups: [OAUTH_COPILOT_OPTGROUP, API_ANTHROPIC_OPTGROUP],
    selectedModel: 'oauth-sonnet-4',
    overrideLevel: 'GLOBAL DEFAULT',
    overrideNote: '',
    fallbackChain: ['GPT-4o', 'Haiku 4'],
    costPerTask: 0.80,
    hasOverride: false,
  },
];

const MOCK_SUB_AGENTS: readonly SubAgentAssignment[] = [
  {
    name: 'code-analyzer',
    parent: 'software-architect',
    iconColor: 'accent',
    icon: '🔍',
    providerType: 'API',
    assignedModel: 'API → Haiku 4',
  },
  {
    name: 'test-generator',
    parent: 'backend-developer',
    iconColor: 'success',
    icon: '🧪',
    providerType: 'CLI',
    assignedModel: 'Claude CLI → Sonnet 4',
  },
  {
    name: 'doc-writer',
    parent: 'team-leader',
    iconColor: 'purple',
    icon: '📝',
    providerType: 'API',
    assignedModel: 'API → Haiku 4',
  },
];

const MOCK_PRESETS: readonly QuickPreset[] = [
  {
    name: 'CLI-First',
    description: 'Use Claude CLI for all agents where available. No API key costs, uses CLI subscription.',
    costLabel: '~$0.00 / TASK',
    badgeType: 'cli',
  },
  {
    name: 'Budget Saver',
    description: 'Use Haiku for all agents except Architect and Security. Minimizes cost.',
    costLabel: '~$4.20 / TASK',
    badgeType: 'budget',
  },
  {
    name: 'Balanced (Recommended)',
    description: 'Opus for leadership, Sonnet for dev, Haiku for reviews. Best value.',
    costLabel: '~$14.92 / TASK',
    badgeType: 'balanced',
  },
  {
    name: 'Maximum Quality',
    description: 'Opus for all critical roles. Best output quality for important features.',
    costLabel: '~$28.50 / TASK',
    badgeType: 'quality',
  },
  {
    name: 'Speed Priority',
    description: 'Haiku + Codex for everything. Fastest execution, lower quality.',
    costLabel: '~$2.80 / TASK',
    badgeType: 'speed',
  },
];

export const MOCK_MODEL_ASSIGNMENTS_DATA: ModelAssignmentsData = {
  scopeTabs: MOCK_SCOPE_TABS,
  hierarchyLevels: MOCK_HIERARCHY_LEVELS,
  assignments: MOCK_ASSIGNMENTS,
  subAgents: MOCK_SUB_AGENTS,
  presets: MOCK_PRESETS,
  totalCostPerTask: 14.92,
  budgetUsed: 59.40,
  budgetTotal: 100,
};
