/**
 * Project Queue Mock Data
 * Static mock task list used by the project page until real API integration.
 */

import { QueueTask } from '../models/project-queue.model';

export const MOCK_QUEUE_TASKS: readonly QueueTask[] = [
  {
    id: 'TASK_2026_155',
    title: 'Project Page — Task Queue Board',
    description: 'Build the main task queue board page with list and kanban views, live status indicators, and filtering capabilities.',
    status: 'IN_PROGRESS',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: 'Dev',
    sessionId: 'SESSION_2026-03-30_04-52-28',
    model: 'claude-sonnet',
    createdAt: '2026-03-30T08:00:00Z',
    lastActivity: '2 min ago',
  },
  {
    id: 'TASK_2026_156',
    title: 'Auto-Pilot Control Panel — Start/Stop/Config',
    description: 'Create the auto-pilot control panel with start, stop, and configuration options for automated task processing.',
    status: 'CREATED',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: null,
    model: null,
    createdAt: '2026-03-30T07:30:00Z',
    lastActivity: '5 min ago',
  },
  {
    id: 'TASK_2026_157',
    title: 'Session Viewer — Live Log Streaming',
    description: 'Implement real-time log streaming viewer for active sessions with WebSocket support and log filtering.',
    status: 'CREATED',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: null,
    model: null,
    createdAt: '2026-03-30T07:30:00Z',
    lastActivity: '5 min ago',
  },
  {
    id: 'TASK_2026_158',
    title: 'Worker Status Grid — Live Worker Health',
    description: 'Build a live worker health monitoring grid showing CPU, memory, and task progress for each active worker.',
    status: 'CREATED',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: null,
    model: null,
    createdAt: '2026-03-30T07:30:00Z',
    lastActivity: '5 min ago',
  },
  {
    id: 'TASK_2026_168',
    title: 'Project Tasks List — Search & Filters',
    description: 'Enhance the project tasks list page with full-text search, multi-select status/type/priority filters, date range filter, sort options, active filter chips, and URL persistence.',
    status: 'IN_PROGRESS',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: 'Dev',
    sessionId: 'SESSION_2026-03-30_10-04-17',
    model: 'glm-5.1',
    createdAt: '2026-03-30T10:00:00Z',
    lastActivity: '1 min ago',
  },
  {
    id: 'TASK_2026_148',
    title: 'Settings Page — API Keys & Provider Config',
    description: 'Create the settings page for managing API keys and AI provider configurations with encrypted storage.',
    status: 'IN_REVIEW',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: 'SESSION_2026-03-29_10-12-00',
    model: 'claude-sonnet',
    createdAt: '2026-03-29T10:00:00Z',
    lastActivity: '1 hour ago',
  },
  {
    id: 'TASK_2026_146',
    title: 'Model Performance Telemetry View',
    description: 'Build telemetry dashboard showing model performance metrics including response times, success rates, and token usage.',
    status: 'COMPLETE',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: null,
    sessionId: null,
    model: 'gpt-4',
    createdAt: '2026-03-28T14:00:00Z',
    lastActivity: '3 hours ago',
  },
  {
    id: 'TASK_2026_145',
    title: 'Phase Timing Telemetry View',
    description: 'Implement phase timing visualization showing duration breakdowns for PM, Architect, Dev, and QA phases.',
    status: 'COMPLETE',
    type: 'TEST',
    priority: 'P2-Medium',
    phase: null,
    sessionId: null,
    model: 'claude-sonnet',
    createdAt: '2026-03-28T12:00:00Z',
    lastActivity: '4 hours ago',
  },
  {
    id: 'TASK_2026_144',
    title: 'Session Comparison Telemetry View',
    description: 'Create a side-by-side session comparison view allowing analysis of different session runs and outcomes.',
    status: 'COMPLETE',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: null,
    sessionId: null,
    model: 'gpt-4',
    createdAt: '2026-03-28T10:00:00Z',
    lastActivity: '5 hours ago',
  },
  {
    id: 'TASK_2026_143',
    title: 'Task Trace Telemetry View',
    description: 'Implement task trace visualization showing the full lifecycle of a task from creation to completion.',
    status: 'IMPLEMENTED',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: null,
    sessionId: 'SESSION_2026-03-28_14-00-00',
    model: 'glm-5.1',
    createdAt: '2026-03-27T16:00:00Z',
    lastActivity: '6 hours ago',
  },
  {
    id: 'TASK_2026_130',
    title: 'New Task Page — Single Textarea Creator',
    description: 'Build the new task creation page with a single textarea for task description and auto-generated metadata.',
    status: 'IMPLEMENTED',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: 'SESSION_2026-03-27_09-00-00',
    model: 'claude-sonnet',
    createdAt: '2026-03-27T09:00:00Z',
    lastActivity: '1 day ago',
  },
  {
    id: 'TASK_2026_110',
    title: 'Agent Editor View',
    description: 'Create the agent editor view for configuring AI agent behaviors, system prompts, and tool access.',
    status: 'FAILED',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: 'Dev',
    sessionId: 'SESSION_2026-03-25_11-30-00',
    model: 'gpt-4',
    createdAt: '2026-03-25T11:00:00Z',
    lastActivity: '2 days ago',
  },
  {
    id: 'TASK_2026_108',
    title: 'Remove OpenAI provider references',
    description: 'Refactor the codebase to remove hardcoded OpenAI provider references and generalize the provider abstraction layer.',
    status: 'BLOCKED',
    type: 'REFACTOR',
    priority: 'P2-Medium',
    phase: null,
    sessionId: null,
    model: null,
    createdAt: '2026-03-24T08:00:00Z',
    lastActivity: '3 days ago',
  },
  {
    id: 'TASK_2026_099',
    title: 'Fix pagination offset in task list API',
    description: 'Fix bug where task list pagination skips the first result when offset is greater than zero.',
    status: 'FAILED',
    type: 'BUGFIX',
    priority: 'P0-Critical',
    phase: 'QA',
    sessionId: 'SESSION_2026-03-23_16-00-00',
    model: 'glm-5.1',
    createdAt: '2026-03-23T16:00:00Z',
    lastActivity: '4 days ago',
  },
  {
    id: 'TASK_2026_085',
    title: 'Update API documentation for v2 endpoints',
    description: 'Update the API documentation to reflect the new v2 endpoint structure including breaking changes and migration guide.',
    status: 'COMPLETE',
    type: 'DOCS',
    priority: 'P3-Low',
    phase: null,
    sessionId: null,
    model: 'claude-sonnet',
    createdAt: '2026-03-20T10:00:00Z',
    lastActivity: '7 days ago',
  },
  {
    id: 'TASK_2026_070',
    title: 'Migrate test suite to Vitest',
    description: 'Migrate the existing Jest-based test suite to Vitest for better performance and ESM support.',
    status: 'CANCELLED',
    type: 'CHORE',
    priority: 'P3-Low',
    phase: null,
    sessionId: null,
    model: null,
    createdAt: '2026-03-18T14:00:00Z',
    lastActivity: '10 days ago',
  },
];
