/**
 * Project Queue Mock Data
 * Static mock task list used by the project page until real API integration.
 */

import { QueueTask } from '../models/project-queue.model';

export const MOCK_QUEUE_TASKS: readonly QueueTask[] = [
  {
    id: 'TASK_2026_155',
    title: 'Project Page — Task Queue Board',
    status: 'IN_PROGRESS',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: 'Dev',
    sessionId: 'SESSION_2026-03-30_04-52-28',
    lastActivity: '2 min ago',
  },
  {
    id: 'TASK_2026_156',
    title: 'Auto-Pilot Control Panel — Start/Stop/Config',
    status: 'CREATED',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: null,
    lastActivity: '5 min ago',
  },
  {
    id: 'TASK_2026_157',
    title: 'Session Viewer — Live Log Streaming',
    status: 'CREATED',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: null,
    lastActivity: '5 min ago',
  },
  {
    id: 'TASK_2026_158',
    title: 'Worker Status Grid — Live Worker Health',
    status: 'CREATED',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: null,
    lastActivity: '5 min ago',
  },
  {
    id: 'TASK_2026_148',
    title: 'Settings Page — API Keys & Provider Config',
    status: 'IN_REVIEW',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: 'SESSION_2026-03-29_10-12-00',
    lastActivity: '1 hour ago',
  },
  {
    id: 'TASK_2026_146',
    title: 'Model Performance Telemetry View',
    status: 'COMPLETE',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: null,
    sessionId: null,
    lastActivity: '3 hours ago',
  },
  {
    id: 'TASK_2026_145',
    title: 'Phase Timing Telemetry View',
    status: 'COMPLETE',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: null,
    sessionId: null,
    lastActivity: '4 hours ago',
  },
  {
    id: 'TASK_2026_144',
    title: 'Session Comparison Telemetry View',
    status: 'COMPLETE',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: null,
    sessionId: null,
    lastActivity: '5 hours ago',
  },
  {
    id: 'TASK_2026_143',
    title: 'Task Trace Telemetry View',
    status: 'IMPLEMENTED',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: null,
    sessionId: 'SESSION_2026-03-28_14-00-00',
    lastActivity: '6 hours ago',
  },
  {
    id: 'TASK_2026_130',
    title: 'New Task Page — Single Textarea Creator',
    status: 'IMPLEMENTED',
    type: 'FEATURE',
    priority: 'P1-High',
    phase: null,
    sessionId: 'SESSION_2026-03-27_09-00-00',
    lastActivity: '1 day ago',
  },
  {
    id: 'TASK_2026_110',
    title: 'Agent Editor View',
    status: 'FAILED',
    type: 'FEATURE',
    priority: 'P2-Medium',
    phase: 'Dev',
    sessionId: 'SESSION_2026-03-25_11-30-00',
    lastActivity: '2 days ago',
  },
  {
    id: 'TASK_2026_108',
    title: 'Remove OpenAI provider references',
    status: 'BLOCKED',
    type: 'REFACTOR',
    priority: 'P2-Medium',
    phase: null,
    sessionId: null,
    lastActivity: '3 days ago',
  },
];
