import { ProviderHubData } from '../models/provider-hub.model';

export const MOCK_PROVIDER_HUB_DATA: ProviderHubData = {
  costSummary: {
    totalCost: 59.40,
    budget: 100,
    costBars: [
      { provider: 'Anthropic', amount: 47.30, percent: 79, colorClass: 'cost-bar-claude' },
      { provider: 'OpenAI', amount: 12.10, percent: 20, colorClass: 'cost-bar-openai' },
    ],
  },
  providers: [
    {
      id: 'anthropic',
      name: 'Anthropic (Claude)',
      subtitle: 'API Provider',
      iconLetter: 'A',
      iconClass: 'icon-claude',
      apiType: 'api',
      connectionStatus: 'connected',
      connectionLabel: 'Connected',
      monthlyCost: 47.30,
      authType: 'api-key',
      maskedKey: 'sk-ant-api03-xxxxxxxxxxxxxxxx',
      baseUrl: '',
      testResult: 'Connection verified — 3 models available, 1.2M tokens used this month',
      models: [
        {
          name: 'Claude Opus 4',
          id: 'claude-opus-4',
          capability: 'high',
          capabilityLabel: 'Reasoning',
          context: '200K',
          inputPrice: '$15',
          outputPrice: '$75',
          enabled: true,
        },
        {
          name: 'Claude Sonnet 4',
          id: 'claude-sonnet-4',
          capability: 'medium',
          capabilityLabel: 'Balanced',
          context: '200K',
          inputPrice: '$3',
          outputPrice: '$15',
          enabled: true,
        },
        {
          name: 'Claude Haiku 4',
          id: 'claude-haiku-4',
          capability: 'fast',
          capabilityLabel: 'Fast',
          context: '200K',
          inputPrice: '$0.25',
          outputPrice: '$1.25',
          enabled: true,
        },
      ],
    },
    {
      id: 'openai',
      name: 'OpenAI (Codex)',
      subtitle: 'API Provider',
      iconLetter: 'O',
      iconClass: 'icon-openai',
      apiType: 'api',
      connectionStatus: 'connected',
      connectionLabel: 'Connected',
      monthlyCost: 12.10,
      authType: 'api-key',
      maskedKey: 'sk-proj-xxxxxxxxxxxxxxxx',
      testResult: 'Connection verified — 3 models available',
      models: [
        {
          name: 'GPT-4o',
          id: 'gpt-4o',
          capability: 'high',
          capabilityLabel: 'Reasoning',
          context: '128K',
          inputPrice: '$5',
          outputPrice: '$15',
          enabled: true,
        },
        {
          name: 'GPT-4o Mini',
          id: 'gpt-4o-mini',
          capability: 'fast',
          capabilityLabel: 'Fast',
          context: '128K',
          inputPrice: '$0.15',
          outputPrice: '$0.60',
          enabled: true,
        },
        {
          name: 'Codex Mini',
          id: 'codex-mini',
          capability: 'medium',
          capabilityLabel: 'Code',
          context: '200K',
          inputPrice: '$1.50',
          outputPrice: '$6',
          enabled: true,
        },
      ],
    },
    {
      id: 'claude-cli',
      name: 'Claude CLI',
      subtitle: 'CLI Provider',
      iconLetter: 'C',
      iconClass: 'icon-claude-cli',
      apiType: 'cli',
      connectionStatus: 'connected',
      connectionLabel: 'Connected',
      monthlyCost: null,
      authType: 'cli',
      cliPath: '/usr/local/bin/claude',
      cliVersion: 'Claude CLI v2.0.3',
      cliInstallMethod: 'Installed via npm',
      noKeyMessage: 'No API key needed — CLI handles authentication directly',
      models: [
        {
          name: 'Claude Opus 4',
          id: 'cli-opus',
          capability: 'high',
          capabilityLabel: 'Reasoning',
          context: '200K',
          inputPrice: 'Included',
          outputPrice: '',
          enabled: true,
        },
        {
          name: 'Claude Sonnet 4',
          id: 'cli-sonnet',
          capability: 'medium',
          capabilityLabel: 'Balanced',
          context: '200K',
          inputPrice: 'Included',
          outputPrice: '',
          enabled: true,
        },
      ],
    },
    {
      id: 'copilot',
      name: 'GitHub Copilot',
      subtitle: 'Connected via OAuth',
      iconLetter: 'G',
      iconClass: 'icon-copilot',
      apiType: 'oauth',
      connectionStatus: 'connected',
      connectionLabel: 'Connected',
      monthlyCost: null,
      authType: 'oauth',
      oauthExpiryDays: 28,
      models: [
        {
          name: 'Copilot',
          id: 'copilot-default',
          capability: 'medium',
          capabilityLabel: 'Code',
          context: '64K',
          inputPrice: 'Included',
          outputPrice: '',
          enabled: true,
        },
      ],
    },
    {
      id: 'google',
      name: 'Google (Gemini)',
      subtitle: 'API Provider',
      iconLetter: 'G',
      iconClass: 'icon-google',
      apiType: 'api',
      connectionStatus: 'disconnected',
      connectionLabel: 'Key expired',
      monthlyCost: null,
      authType: 'api-key',
      maskedKey: 'AIzaSy-xxxxxxxxxxxxxxxx',
      models: [
        {
          name: 'Gemini 2.5 Pro',
          id: 'gemini-2.5-pro',
          capability: 'high',
          capabilityLabel: 'Reasoning',
          context: '1M',
          inputPrice: '$1.25',
          outputPrice: '$10',
          enabled: true,
        },
        {
          name: 'Gemini 2.5 Flash',
          id: 'gemini-2.5-flash',
          capability: 'fast',
          capabilityLabel: 'Fast',
          context: '1M',
          inputPrice: '$0.15',
          outputPrice: '$0.60',
          enabled: true,
        },
      ],
    },
  ],
  bottomPanel: {
    totalProviders: 5,
    connected: 4,
    expired: 1,
    notConfigured: 0,
  },
};
