import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type Database from 'better-sqlite3';
import type { ToolResult } from './types.js';
import { normalizeSessionId } from './session-id.js';

const VALID_STATUSES = new Set([
  'CREATED', 'IN_PROGRESS', 'IMPLEMENTED', 'IN_REVIEW',
  'FIXING', 'COMPLETE', 'FAILED', 'BLOCKED', 'CANCELLED',
]);

export function writeStatusFile(projectRoot: string, taskId: string, status: string): void {
  const taskDir = join(projectRoot, 'task-tracking', taskId);
  try {
    if (!existsSync(taskDir)) {
      mkdirSync(taskDir, { recursive: true });
    }
    writeFileSync(join(taskDir, 'status'), status, 'utf-8');
  } catch {
    // best-effort — don't fail the DB update if fs write fails
  }
}

export function generateRegistryFromDb(db: Database.Database, projectRoot: string): void {
  const registryPath = join(projectRoot, 'task-tracking', 'registry.md');
  try {
    const rows = db.prepare(
      'SELECT id, status, type, title, created_at FROM tasks ORDER BY id',
    ).all() as Array<{ id: string; status: string; type: string; title: string; created_at: string }>;

    const lines = rows.map((row) => {
      const created = row.created_at?.includes('T') ? row.created_at.split('T')[0] : (row.created_at ?? 'Unknown');
      const safeTitle = (row.title ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
      return `| ${row.id} | ${(row.status ?? 'CREATED').padEnd(11)} | ${(row.type ?? '').padEnd(7)} | ${safeTitle} | ${created} | default |`;
    });

    const output = [
      '<!-- DO NOT EDIT — generated by nitro-fueled status -->',
      '# Task Registry',
      '',
      '| Task ID       | Status      | Type    | Description                        | Created    | Model |',
      '|---------------|-------------|---------|------------------------------------|------------|-------|',
      ...lines,
      '',
    ].join('\n');

    writeFileSync(registryPath, output, 'utf-8');
  } catch {
    // best-effort
  }
}

const UPDATABLE_COLUMNS = new Set([
  'title', 'type', 'priority', 'status', 'complexity', 'model',
  'dependencies', 'description', 'acceptance_criteria', 'file_scope',
  'session_claimed', 'claimed_at',
]);

export function handleGetTasks(
  db: Database.Database,
  args: { status?: string; type?: string; priority?: string; unblocked?: boolean; limit?: number },
): { content: Array<{ type: 'text'; text: string }> } {
  const conditions: string[] = [];
  const params: unknown[] = [];

  if (args.status) {
    conditions.push('status = ?');
    params.push(args.status);
  }
  if (args.type) {
    conditions.push('type = ?');
    params.push(args.type);
  }
  if (args.priority) {
    conditions.push('priority = ?');
    params.push(args.priority);
  }

  const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
  const limit = args.limit !== undefined ? Math.min(Math.max(1, Math.trunc(args.limit)), 200) : undefined;
  const limitClause = limit !== undefined ? ' LIMIT ?' : '';
  const queryParams = limit !== undefined ? [...params, limit] : params;
  const rows = db.prepare(`SELECT * FROM tasks ${where} ORDER BY id${limitClause}`).all(...queryParams) as Array<Record<string, unknown>>;

  if (args.unblocked) {
    const completeTasks = new Set(
      (db.prepare("SELECT id FROM tasks WHERE status = 'COMPLETE'").all() as Array<{ id: string }>).map(r => r.id),
    );
    const filtered = rows.filter(row => {
      let deps: unknown;
      try {
        deps = JSON.parse((row['dependencies'] as string) ?? '[]');
      } catch {
        deps = [];
      }
      if (!Array.isArray(deps)) deps = [];
      return (deps as string[]).length === 0 || (deps as string[]).every(d => completeTasks.has(d));
    });
    return { content: [{ type: 'text' as const, text: JSON.stringify(filtered, null, 2) }] };
  }

  return { content: [{ type: 'text' as const, text: JSON.stringify(rows, null, 2) }] };
}

export function handleClaimTask(
  db: Database.Database,
  args: { task_id: string; session_id: string },
): { content: Array<{ type: 'text'; text: string }> } {
  const now = new Date().toISOString();
  const sessionId = normalizeSessionId(args.session_id);

  const result = db.transaction(() => {
    const row = db.prepare(
      'SELECT session_claimed FROM tasks WHERE id = ? AND (session_claimed IS NULL OR session_claimed = ?)',
    ).get(args.task_id, sessionId) as { session_claimed: string | null } | undefined;

    if (!row) {
      const existing = db.prepare('SELECT session_claimed FROM tasks WHERE id = ?').get(args.task_id) as { session_claimed: string | null } | undefined;
      if (!existing) {
        return { ok: false, reason: 'task_not_found' };
      }
      return { ok: false, claimed_by: existing.session_claimed ? normalizeSessionId(existing.session_claimed) : null };
    }

    db.prepare(
      'UPDATE tasks SET session_claimed = ?, claimed_at = ?, status = ?, updated_at = ? WHERE id = ?',
    ).run(sessionId, now, 'IN_PROGRESS', now, args.task_id);

    return { ok: true };
  })();

  return { content: [{ type: 'text' as const, text: JSON.stringify(result) }] };
}

export function handleReleaseTask(
  db: Database.Database,
  args: { task_id: string; new_status: string },
): { content: Array<{ type: 'text'; text: string }> } {
  const now = new Date().toISOString();
  const info = db.prepare(
    'UPDATE tasks SET session_claimed = NULL, claimed_at = NULL, status = ?, updated_at = ? WHERE id = ?',
  ).run(args.new_status, now, args.task_id);

  if (info.changes === 0) {
    return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: 'task_not_found' }) }] };
  }
  return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: true }) }] };
}

// UPSERTABLE_COLUMNS mirrors UPDATABLE_COLUMNS but excludes session_claimed/claimed_at,
// which are managed by claim_task/release_task to preserve claim atomicity.
const UPSERTABLE_COLUMNS = new Set([
  'title', 'type', 'priority', 'status', 'complexity', 'model',
  'dependencies', 'description', 'acceptance_criteria', 'file_scope',
]);

export function handleUpsertTask(
  db: Database.Database,
  args: { task_id: string; fields: Record<string, unknown> },
): ToolResult {
  const now = new Date().toISOString();

  const existing = db.prepare('SELECT id FROM tasks WHERE id = ?').get(args.task_id) as { id: string } | undefined;

  if (existing) {
    // UPDATE path — rejects non-whitelisted columns; mirrors handleUpdateTask behavior
    const sets: string[] = [];
    const params: unknown[] = [];

    for (const [key, value] of Object.entries(args.fields)) {
      if (!UPSERTABLE_COLUMNS.has(key)) {
        return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: `column '${key}' not updatable` }) }] };
      }
      sets.push(`${key} = ?`);
      const serialized = typeof value === 'object' && value !== null ? JSON.stringify(value) : value;
      params.push(serialized);
    }

    if (sets.length === 0) {
      return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: 'no fields provided' }) }] };
    }

    sets.push('updated_at = ?');
    params.push(now);
    params.push(args.task_id);

    try {
      db.prepare(`UPDATE tasks SET ${sets.join(', ')} WHERE id = ?`).run(...params);
    } catch (err) {
      return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: err instanceof Error ? err.message : String(err) }) }] };
    }

    return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: true, action: 'updated' }) }] };
  }

  // INSERT path — title, type, priority required; all other fields optional
  const fields = args.fields;
  const title = fields.title as string | undefined;
  const type = fields.type as string | undefined;
  const priority = fields.priority as string | undefined;
  const status = (fields.status as string | undefined) ?? 'CREATED';

  if (!title || !type || !priority) {
    return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: 'title, type, and priority are required for insert' }) }] };
  }

  const complexity = (fields.complexity as string | null) ?? null;
  const model = (fields.model as string | null) ?? null;
  const dependencies = typeof fields.dependencies === 'object' && fields.dependencies !== null
    ? JSON.stringify(fields.dependencies) : ((fields.dependencies as string | null) ?? '[]');
  const description = (fields.description as string | null) ?? null;
  const acceptanceCriteria = (fields.acceptance_criteria as string | null) ?? null;
  const fileScope = typeof fields.file_scope === 'object' && fields.file_scope !== null
    ? JSON.stringify(fields.file_scope) : ((fields.file_scope as string | null) ?? '[]');

  try {
    db.prepare(
      `INSERT INTO tasks (id, title, type, priority, status, complexity, model, dependencies, description, acceptance_criteria, file_scope, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    ).run(args.task_id, title, type, priority, status, complexity, model, dependencies, description, acceptanceCriteria, fileScope, now, now);
  } catch (err) {
    return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: err instanceof Error ? err.message : String(err) }) }] };
  }

  return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: true, action: 'inserted' }) }] };
}

export function handleUpdateTask(
  db: Database.Database,
  args: { task_id: string; fields: Record<string, unknown> },
  projectRoot?: string,
): { content: Array<{ type: 'text'; text: string }> } {
  const sets: string[] = [];
  const params: unknown[] = [];

  for (const [key, value] of Object.entries(args.fields)) {
    if (!UPDATABLE_COLUMNS.has(key)) {
      return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: `column '${key}' not updatable` }) }] };
    }
    sets.push(`${key} = ?`);
    const serialized = typeof value === 'object' && value !== null ? JSON.stringify(value) : value;
    params.push(serialized);
  }

  if (sets.length === 0) {
    return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: 'no fields provided' }) }] };
  }

  sets.push('updated_at = ?');
  params.push(new Date().toISOString());
  params.push(args.task_id);

  const info = db.prepare(`UPDATE tasks SET ${sets.join(', ')} WHERE id = ?`).run(...params);

  if (info.changes === 0) {
    return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: false, reason: 'task_not_found' }) }] };
  }

  // Keep status file and registry.md in sync with DB
  if (projectRoot !== undefined) {
    const newStatus = args.fields['status'];
    if (typeof newStatus === 'string' && VALID_STATUSES.has(newStatus)) {
      writeStatusFile(projectRoot, args.task_id, newStatus);
    }
    generateRegistryFromDb(db, projectRoot);
  }

  return { content: [{ type: 'text' as const, text: JSON.stringify({ ok: true }) }] };
}

function detectOrphanedClaims(db: Database.Database): Array<{
  task_id: string;
  title: string;
  status: string;
  claimed_by: string;
  claimed_at: string;
  stale_for_ms: number;
}> {
  const now = Date.now();

  const claimedTasks = db.prepare(
    `SELECT id, title, status, session_claimed, claimed_at, claim_timeout_ms
     FROM tasks
     WHERE session_claimed IS NOT NULL
       AND status IN ('CREATED', 'IN_PROGRESS')`,
  ).all() as Array<{
    id: string;
    title: string;
    status: string;
    session_claimed: string;
    claimed_at: string | null;
    claim_timeout_ms: number | null;
  }>;

  const activeSessions = new Set(
    (db.prepare("SELECT id FROM sessions WHERE loop_status = 'running'").all() as Array<{ id: string }>).map(s => s.id),
  );

  const orphaned: Array<{
    task_id: string;
    title: string;
    status: string;
    claimed_by: string;
    claimed_at: string;
    stale_for_ms: number;
  }> = [];

  for (const task of claimedTasks) {
    const claimedAt = task.claimed_at ? new Date(task.claimed_at).getTime() : 0;
    const claimTimeout = task.claim_timeout_ms ?? null;

    const isSessionDead = !activeSessions.has(task.session_claimed);
    const isTtlExpired = claimTimeout !== null && (now - claimedAt) > claimTimeout;

    if (isSessionDead || isTtlExpired) {
      orphaned.push({
        task_id: task.id,
        title: task.title,
        status: task.status,
        claimed_by: task.session_claimed,
        claimed_at: task.claimed_at ?? '',
        stale_for_ms: now - claimedAt,
      });
    }
  }

  return orphaned;
}

export function handleGetOrphanedClaims(
  db: Database.Database,
): { content: Array<{ type: 'text'; text: string }> } {
  const orphaned = detectOrphanedClaims(db);

  return { content: [{ type: 'text' as const, text: JSON.stringify({ orphaned }, null, 2) }] };
}

export function handleReleaseOrphanedClaims(
  db: Database.Database,
): { content: Array<{ type: 'text'; text: string }> } {
  const orphaned = detectOrphanedClaims(db);
  const now = new Date().toISOString();
  const releasedTaskIds: string[] = [];

  for (const task of orphaned) {
    const claimedAt = task.claimed_at ? new Date(task.claimed_at).getTime() : 0;
    const staleForMs = Date.now() - claimedAt;

    db.prepare(
      `UPDATE tasks
       SET session_claimed = NULL, claimed_at = NULL, status = 'CREATED', updated_at = ?
       WHERE id = ?`,
    ).run(now, task.task_id);

    releasedTaskIds.push(task.task_id);

    const eventData = JSON.stringify({
      task_id: task.task_id,
      was_claimed_by: task.claimed_by,
      stale_for_ms: staleForMs,
    });

    db.prepare(
      `INSERT INTO events (session_id, task_id, source, event_type, data)
       VALUES (?, ?, ?, ?, ?)`,
    ).run('system', task.task_id, 'orphan_recovery', eventData);
  }

  return {
    content: [{
      type: 'text' as const,
      text: JSON.stringify({
        released: releasedTaskIds.length,
        tasks: releasedTaskIds,
      }, null, 2),
    }],
  };
}
