import { spawnSync } from 'node:child_process';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { logger } from './logger.js';
import type { ProjectProfile } from './stack-detect.js';

/** An agent file entry from batch generation */
export interface GeneratedAgent {
  name: string;
  content: string;
}

/** Result from single-pass artifact generation */
export interface ArtifactGenerationResult {
  claudeNitroMd: string | null;
  antiPatterns: string | null;
  agents: GeneratedAgent[];
}

/** Allowlist for AI-returned agent names — prevents path traversal */
const AGENT_NAME_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;
const MAX_AGENT_CONTENT_LEN = 50_000;
const MAX_CONTENT_LEN = 30_000;

function isRecord(val: unknown): val is Record<string, unknown> {
  return typeof val === 'object' && val !== null && !Array.isArray(val);
}

function buildPrompt(profile: ProjectProfile, baseTemplate: string): string {
  return `You are generating project-specific configuration files for a software project, based on its ProjectProfile.

PROJECT PROFILE:
${JSON.stringify(profile, null, 2)}

BASE TEMPLATE FOR CLAUDE.NITRO.MD (use as starting structure, then customize with profile data):
${baseTemplate}

Generate three artifacts as a single JSON object with this exact structure:
{
  "claudeNitroMd": "<full content of .nitro/CLAUDE.nitro.md>",
  "antiPatterns": "<full content of .claude/anti-patterns.md>",
  "agents": [
    {
      "name": "<kebab-case agent name matching profile.agents[].name>",
      "content": "<full markdown content of the agent .md file>"
    }
  ]
}

REQUIREMENTS:

claudeNitroMd:
- Under 200 lines total
- Start with "# Nitro-Fueled Conventions"
- Include a "## Project Stack" section listing the actual detected stack from profile.stack
- Include a "## Architecture" section with profile.architecturePatterns
- Include a "## Naming Conventions" section with profile.namingConventions
- Include a "## Folder Organization" section with profile.folderOrganization
- Keep the Orchestration and Task States sections from the base template
- End with a comment: "> Generated by nitro-fueled init from workspace analysis"

antiPatterns:
- Start with "# Anti-Patterns — Project Rules"
- Include this line: "Check these BEFORE submitting work."
- List 5-15 specific anti-patterns for this project based on profile.antiPatterns, profile.stack, and profile.architecturePatterns
- Use "## Rule N: <Title>" headings for each rule
- Each rule: one-line description of what to avoid and why

agents:
- One entry per agent in profile.agents
- Each agent file MUST start with YAML frontmatter:
  ---
  name: <name>
  description: <one-sentence description for this specific tech stack>
  ---
- Then a short "# <Title>" heading and a 3-5 sentence role description
- Keep under 80 lines each
- Focus on the specific technology (e.g., Angular Developer focuses on Angular patterns, not generic advice)

IMPORTANT: Return ONLY the JSON object. No markdown code fences. No explanation text before or after.`;
}

function parseResponse(responseText: string): ArtifactGenerationResult | null {
  let cleaned = responseText.trim();
  // Strip markdown fences if present
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\s*/, '').replace(/\s*```$/, '');
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch {
    return null;
  }

  if (!isRecord(parsed)) return null;

  const rawClaude = parsed['claudeNitroMd'];
  const claudeNitroMd =
    typeof rawClaude === 'string' ? rawClaude.slice(0, MAX_CONTENT_LEN) : null;

  const rawAp = parsed['antiPatterns'];
  const antiPatterns =
    typeof rawAp === 'string' ? rawAp.slice(0, MAX_CONTENT_LEN) : null;

  const rawAgents = parsed['agents'];
  const agents: GeneratedAgent[] = [];
  if (Array.isArray(rawAgents)) {
    for (const entry of rawAgents) {
      if (!isRecord(entry)) continue;
      if (typeof entry['name'] !== 'string' || typeof entry['content'] !== 'string') continue;
      // Validate name against allowlist — prevents path traversal via AI-returned agent name
      if (!AGENT_NAME_RE.test(entry['name'])) continue;
      agents.push({
        name: entry['name'],
        content: entry['content'].slice(0, MAX_AGENT_CONTENT_LEN),
      });
    }
  }

  return { claudeNitroMd, antiPatterns, agents };
}

/**
 * Run a single AI call to generate all project-specific artifacts from a ProjectProfile.
 *
 * This replaces:
 * - N individual `claude -p /create-agent` calls (one per developer agent)
 * - Template-based CLAUDE.nitro.md with a profile-aware generated version
 * - Tag-filtered anti-patterns.md with AI-generated project-specific patterns
 *
 * Returns null if the AI call fails or the response cannot be parsed.
 * Callers should fall back to the static/tag-filter paths in that case.
 */
export function generateArtifactsFromProfile(
  profile: ProjectProfile,
  baseTemplate: string,
): ArtifactGenerationResult | null {
  const promptContent = buildPrompt(profile, baseTemplate);

  const result = spawnSync('claude', ['-p', promptContent, '--output-format', 'text'], {
    stdio: ['ignore', 'pipe', 'pipe'],
    timeout: 180_000,
    maxBuffer: 4 * 1024 * 1024,
  });

  if (result.status !== 0 || result.signal !== null) {
    const stderr = result.stderr?.toString().trim() ?? '';
    if (stderr !== '') {
      logger.error(`  Artifact generation failed: ${stderr.slice(0, 200)}`);
    }
    return null;
  }

  const stdout = result.stdout?.toString().trim() ?? '';
  if (stdout === '') return null;

  const parsed = parseResponse(stdout);
  if (parsed === null) {
    logger.error('  Artifact generation: could not parse AI response');
  }
  return parsed;
}

/**
 * Write a generated CLAUDE.nitro.md to .nitro/CLAUDE.nitro.md.
 * Returns the written path on success, or null if skipped/failed.
 */
export function writeClaudeNitroMd(
  cwd: string,
  content: string,
  overwrite: boolean,
): string | null {
  const dest = resolve(cwd, '.nitro', 'CLAUDE.nitro.md');
  if (!overwrite && existsSync(dest)) return null;
  try {
    mkdirSync(resolve(cwd, '.nitro'), { recursive: true });
    writeFileSync(dest, content, 'utf-8');
    return dest;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`  Warning: Could not write CLAUDE.nitro.md: ${msg}`);
    return null;
  }
}

/**
 * Write a generated anti-patterns.md to .claude/anti-patterns.md.
 * Returns the written path on success, or null if skipped/failed.
 */
export function writeAntiPatternsMd(
  cwd: string,
  content: string,
  overwrite: boolean,
): string | null {
  const dest = resolve(cwd, '.claude', 'anti-patterns.md');
  if (!overwrite && existsSync(dest)) return null;
  try {
    mkdirSync(resolve(cwd, '.claude'), { recursive: true });
    writeFileSync(dest, content, 'utf-8');
    return dest;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`  Warning: Could not write anti-patterns.md: ${msg}`);
    return null;
  }
}

/**
 * Write generated developer agent files to .claude/agents/.
 * Skips agents that already exist (never overwrites agent files).
 * Returns the list of written file paths.
 */
export function writeAgentFiles(cwd: string, agents: GeneratedAgent[]): string[] {
  const agentsDir = resolve(cwd, '.claude', 'agents');
  const written: string[] = [];

  for (const agent of agents) {
    const dest = resolve(agentsDir, `${agent.name}.md`);
    if (existsSync(dest)) continue;
    try {
      mkdirSync(agentsDir, { recursive: true });
      writeFileSync(dest, agent.content, 'utf-8');
      written.push(dest);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`  Warning: Could not write agent ${agent.name}: ${msg}`);
    }
  }

  return written;
}
